### PR TITLE
Feature delay microseconds

### PR DESCRIPTION
**Pull request by cburstedde**
Hi, I've looked into delayMicroseconds() and added the 22.1184 and 18 MHz frequencies.

I've also added tests so they should work now with 0 at frequencies >= 24 MHz.

This PR is untested but everything compiles and looks decent. :)

### CODE REVIEW

**Comment by MCUdude** [comment]
Thanks! I just tried with 22.1184MHz and 18 MHz. delayMicroseconds are **spot-on**!

Would you like to add 22.1184 and 18 MHz to the list of supported clock frequencies in the README?

**Comment by cburstedde** [comment]
Thanks!  :) I'll be happy to, but technically that is only legitimate after merging the millis and micros code. The unpatched millis code is a couple percent off for some odd frequencies due to that roundoff in the F_CPU macro at the top.

**Comment by MCUdude** [comment]
>  I'll be happy to, but technically that is only legitimate after merging the millis and micros code.

Yes, you're right. I can fix it myself when these three PRs are merged.

**Comment by cburstedde** [comment]
> > I'll be happy to, but technically that is only legitimate after merging the millis and micros code.
> 
> Yes, you're right. I can fix it myself when these three PRs are merged.

Cool, I'm also holding back on making a PR out of my alternate micros method which has all the merges and an updated README. Getting #24, #25 and #26 integrated first sounds good to me.

**Pull request merged**
