### PR TITLE
Accurate timing for 18.432MHz & 24MHz

### PR DESCRIPTION
**Pull request by Jackjan4**
This PR adds accurate timing for 18.432MHz based on @SpenceKonde great code from his ATTinyCore.
Also, this adds a bit of stub code for the possibility to add support for 24MHz  (which I will do in a couple of days(maybe weeks))

### CODE REVIEW

**Comment by MCUdude** [comment]
Great! I'll do some testing with the same setup as last time. Do you want to add a 18.432 MHz option for delayMicroseconds as well?

**Comment by Jackjan4** [comment]
I will add correct delayMicroseconds() with my 24MHz PR :)

**Comment by MCUdude** [comment]
This works perfectly! delay(1000) now lasts 0.993 seconds instead of 1.157 seconds.

**Comment by Jackjan4** [comment]
Awesome! :) Soon we'll have good accuracy on all relevant clocks 😃

**Comment by MCUdude** [comment]
If you're in the mood feel free to add micros and delayMicroseconds for other weird clock frequencies as well. There are bootloaders available for 14.7456MHz, 11.0592MHz, 7.3728MHz, 3.6864MHz and 1.8432MHz. I can do the testing if you don't have any crystals to test with 🙂

**Comment by obskyr** [comment]
Whoa! @Jackjan4 (and @SpenceKonde) , you're the best! :star:

Holding out for `delayMicroseconds()`, but when that's in there, all my problems are solved. :grin:

**Comment by Jackjan4** [comment]
The commits above improve accuracy of delayMicroseconds() for 18.432MHz, **however** I'm not able to test how much (if it is even measurable) it improved the accuracy, since I don't have any 18.432MHz crystals here. So please be aware that this is a bit experimental. Maybe I could improve accuracy even more if someone could give me his "before & after test measurements" and provide me some facts.

**Comment by MCUdude** [comment]
Thanks! Don't worry about the hardware. I'm well covered.

gen scope

Here's some results based on the code below:

| delayMicroseconds() | Actual time high | Actual time low |
|---------------------|------------------|-----------------|
| 1                   | 0.977            | 1.085           |
| 2                   | 2.226            | 2.330           |
| 3                   | 3.310            | 3.410           |
| 4                   | 4.395            | 4.500           |
| 5                   | 5.480            | 5.585           |
| 10                  | 10.91            | 11.00           |
| 50                  | 54.35            | 54.40           |
| 100                 | 108.5            | 108.8           |
| 500                 | 547.5            | 549.0           |
| 1000                | 1095             | 1095            |
| 5000                | 5455             | 5455            |
| 10000               | 10910            | 10910           |

I hope this give you an idea. It seems to be a tiny bit slow. Not sure if it's possible to do anything about it.

``` c
void setup() 
{
  DDRA |= _BV(PA7);
  cli();
}

void loop() 
{
  while(1)
  {
    PORTA = 0x80;
    delayMicroseconds(2);
    PORTA = 0x00;
    delayMicroseconds(2);
  } 
}
```

**Comment by Jackjan4** [comment]
Thanks for the results :) Indeed its kinds tricky to get 18.432MHz accurate since the method, which is used in the core, needs clock frequencies which are divisible by 4 to be accurate. I'd be glad you could also measure the precision before my commits, so I could get an idea if I'm heading in the right direction.

**Comment by MCUdude** [comment]
You should probably focus on the HIGH time, since this is not affected by the jump instruction in order to rin the loop again.

IIRC it takes two instructions (SBI or CBI) to set a PORT high or low. A little math tells me that this "adds" 0.109us to the pulse length.

Don't worry about the LOW time. It takes either 2 or 3 instructions to start at the beginning of the while loop.

EDIT:
You shouldn't worry too much about the last decimal in my measurements. The scope (Rigol 1054Z) does on-screen measurements, so it is not as accurate as a dedicated frequency counter is.

**Comment by obskyr** [comment]
To be fair, in the specific case of `delay` and `delayMicroseconds`, it's better to be a bit slow than to be a bit fast. If you do `delayMicroseconds(5)` to accommodate a MOSFET's switching time, for example, it's nice to be guaranteed a delay of at *least* 5 microseconds. Atmel agreed with this philosophy, apparently, since [`_delay_ms`](https://www.microchip.com/webdoc/AVRLibcReferenceManual/group__util__delay_1gad22e7a36b80e2f917324dc43a425e9d3.html) and [`_delay_us`](https://www.microchip.com/webdoc/AVRLibcReferenceManual/group__util__delay_1gab20bfffeacc678cb960944f5519c0c4f.html) guarantee the delays to not be shorter than the provided value.

**Comment by MCUdude** [comment]
Last commit doesn't seem to do much. I pretty much have the exact same readings..

**Comment by Jackjan4** [comment]
This commit removes a bit of time on very small delays (2-20), to be a bit more accurate.
However, I think, more improvements aren't doable with the method that is used in the core. To be more precise, a new specific loop specifically for odd clocks must be created.
@MCUdude I would be really grateful if you could do a measurement for delay accuracy before all my commits and after all these. This comparison could help me very much :)

**Comment by MCUdude** [comment]
> @MCUdude I would be really grateful if you could do a measurement for delay accuracy before all my commits and after all these. This comparison could help me very much :)

Sure! It takes some time writing down all the results. Is it OK if I only measure the high pulse? And how many readings do you want me to take? I can do it for 1, 2, 3, 4, 5, 10, 100, 1000 and 10000 if that's OK?

**Comment by Jackjan4** [comment]
@MCUdude The high pulse is definitly enough. I only need some representative numbers like 1,2,5,10,50,100,500,1000,10000. That would be really great! :)

**Comment by MCUdude** [comment]
I'm on the case! Results are ready in a few minutes

**Comment by MCUdude** [comment]
| delayMicroseconds() | ON time before PR | ON time after PR |
|---------------------|-------------------|------------------|
| 1                   | 0.814             | 0.977            |
| 2                   | 1.680             | 2.006            |
| 3                   | 2.555             | 3.095            |
| 4                   | 3.410             | 4.175            |
| 5                   | 4.285             | 5.265            |
| 10                  | 8.630             | 10.69            |
| 50                  | 43.35             | 54.05            |
| 100                 | 86.70             | 108.3            |
| 500                 | 433.5             | 542.5            |
| 1000                | 868.0             | 1085             |
| 5000                | 4345              | 5425             |
| 10000               | 8690              | 10850            |

**Comment by Jackjan4** [comment]
Awesome! Thanks for this chart. I already think I maybe got a good workaround. I will do an experimental commit in a couple of minutes.

**Comment by Jackjan4** [comment]
This commit is a bit experimental but establishes a very good method which can be used on all odd clocks when calculated correctly. Seeings test results would be great! :) The results can be very out of place but I think this is how a good experiment starts 😋 

EDIT: This method **does not** ensure that delayMicros(X) delays _at least_ X microseconds, but I will add this, if some test charts show good results.

**Comment by MCUdude** [comment]
delayMicroseconds(2) acts weird. it's on for 142000 us!

EDIT:
It seems to be caused by the last line. changing it back to us -= 7; solves the problem

**Comment by Jackjan4** [comment]
> 
> 
> demayMicroseconds(2) acts weird. it's on for 142000 us!

Yeah, kind of expected something like this for small numbers 😄  Will fix this.

**Comment by obskyr** [comment]
Possibly relevant quote from the Arduino documentation of `delayMicroseconds`:

> This function works very accurately in the range 3 microseconds and up. We cannot assure that delayMicroseconds will perform precisely for smaller delay-times.

**Comment by MCUdude** [comment]
BTW is the last commit supposed to be accurate with high or low us numbers? I edited the last line with `us -= 7;`, and ran the 2 us test again. High pulse seems to last 3.145us

**Comment by Jackjan4** [comment]
> 
> 
> BTW is the last commit supposed to be accurate with high or low us numbers? I edited the last line with `us -= 7;`, and ran the 2 us test again. High pulse seems to last 3.145us

It should be more accurate with big numbers. For smaller ones (2 to 5 probably) I maybe need to make special checks.

**Comment by MCUdude** [comment]
Here's the results from your last commit. (Measurements done with us -= 8;)

| delayMicroseconds() | Actual delay time after last commit |
|---------------------|-------------------------------------|
| 10                  | 10.53                               |
| 50                  | 48.50                               |
| 100                 | 96.00                               |
| 500                 | 475.5                               |
| 1000                | 951.0                               |
| 5000                | 4745                                |
| 10000               | 9490                                |

**Comment by Jackjan4** [comment]
Now we are getting somewhere. This next commit is increasing the delay time slightly.

**Comment by MCUdude** [comment]
Here are the results from the last measurement:

| delayMicroseconds() | Actual delay time after last commit |
|---------------------|-------------------------------------|
| 5                   | 5.260                               |
| 10                  | 10.69                               |
| 25                  | 27.05                               |
| 50                  | 52.65                               |
| 100                 | 103.6                               |
| 500                 | 510.5                               |
| 1000                | 1019                                |
| 5000                | 5085                                |
| 10000               | 10170                               |

**Comment by Jackjan4** [comment]
Seems like a good decrease in time since the very first chart. Will look into more improvements.

**Comment by MCUdude** [comment]
I've also measured from 1-4 us:

| delayMicroseconds() | Actual delay time after last commit |
|---------------------|-------------------------------------|
| 1                   | 0.978                               |
| 2                   | 2.008                               |
| 3                   | 3.095                               |
| 4                   | 4.175                               |

We're very close now. Are there room for more improvements?

**Comment by Jackjan4** [comment]
The problem is: We could go more precise for larger numbers with more bitshifts, however this results in losing accuracy for small numbers. In the last commit I increased the subtraction factor by 1 which decreases the time for all numbers a bit, but this has no larger impact. So I think elegant optimizing ends here without adding nasty if-cases for small, medium, large numbers, etc.
However, this PR results in some good improvements for delayMicroseconds() :)

PS: If you want, I can make delayMicroseconds(1) one cycle longer, so it definitly delays at least 1us.

**Comment by MCUdude** [comment]
Great! I'll test it right away. Please make delayMicroseconds(1) one cycle longer 👍

**Comment by Jackjan4** [comment]
Btw, Measurements of delays for 9,10,11,12 are interesting to analyze since they show when the correction factor kicks in.

**Comment by MCUdude** [comment]
Latest results!  We might have tipped over..

| delayMicroseconds() | Actual delay time after last commit |
|---------------------|-------------------------------------|
| 1                   | 1.031                               |
| 2                   | 2.062                               |
| 3                   | 3.145                               |
| 4                   | 4.230                               |
| 5                   | 5.315                               |
| 9                   | 9.650                               |
| 10                  | 10.75                               |
| 11                  | 12.52                               |
| 12                  | 13.82                               |
| 25                  | 26.80                               |
| 50                  | 52.45                               |
| 100                 | 103.5                               |
| 500                 | 510.5                               |
| 1000                | 1019                                |
| 5000                | 5085                                |
| 10000               | 10170                               |

**Comment by Jackjan4** [comment]
Interesting! Seems like my code adds much more overhead than I expected. I will increase the subtraction factor even more till delayMicroseconds(11) will fit perfectly.

**Comment by MCUdude** [comment]
Here's the latest results. It does seem lie commit e585c21 was the most accurate one in the lower region.
However I really need to go to bed. I may continue with the test's when I'm home from work!

| delayMicroseconds() | Actual delay time after last commit |
|---------------------|-------------------------------------|
| 1                   | 1.031                               |
| 2                   | 2.062                               |
| 3                   | 3.145                               |
| 4                   | 4.235                               |
| 5                   | 5.310                               |
| 9                   | 9.650                               |
| 10                  | 10.75                               |
| 11                  | 11.90                               |
| 12                  | 13.18                               |
| 25                  | 26.20                               |
| 50                  | 51.80                               |
| 100                 | 102.9                               |
| 500                 | 509.5                               |
| 1000                | 1019                                |
| 5000                | 5085                                |
| 10000               | 10170                               |

**Comment by Jackjan4** [comment]
Alright, of course! Thank you very much for all your detailed measurements :)

**Comment by Jackjan4** [comment]
Increasing multiplication factor again & switched if statement to maybe get a cycle less for small delays.
Additionally, we don't need so much measurements anymore. 2, 3 and 9-12 are perfectly enough.

**Comment by Jackjan4** [comment]
I also had the time to add accurate 24MHz delay() timing 😋 This can be tested very easily, because it should be very accurate.

**Comment by MCUdude** [comment]
Here's the result after your latest commit (18.432MHz).

| delayMicroseconds() | Actual delay time after last commit |
|---------------------|-------------------------------------|
| 1                   | 1.031                               |
| 2                   | 2.116                               |
| 3                   | 3.205                               |
| 4                   | 4.285                               |
| 5                   | 5.375                               |
| 9                   | 9.710                               |
| 10                  | 10.78                               |
| 11                  | 11.18                               |
| 12                  | 12.48                               |
| 25                  | 25.45                               |
| 50                  | 51.15                               |
| 100                 | 102.1                               |
| 500                 | 509.0                               |
| 1000                | 1017                                |
| 5000                | 5085                                |
| 10000               | 10170                               |

**Comment by Jackjan4** [comment]
Big numbers look very good now. However, switching the if-statements seems to make it worse for the small ones. I will roll that change back and will lower the correction barrier, so maybe small numbers like 10 or 9 especially can benefit from the correction.

**Comment by MCUdude** [comment]
Results from last commit.It seems to be a little slower from 11 -> 500. I'm not able to measure sub microseconds after we pass 1000us. I only have four digits of precision.

| delayMicroseconds() | Actual delay time after last commit |
|---------------------|-------------------------------------|
| 1                   | 1.031                               |
| 2                   | 2.062                               |
| 3                   | 3.145                               |
| 4                   | 4.235                               |
| 5                   | 5.315                               |
| 9                   | 9.650                               |
| 10                  | 10.78                               |
| 11                  | 11.46                               |
| 12                  | 12.74                               |
| 25                  | 25.75                               |
| 50                  | 51.35                               |
| 100                 | 102.3                               |
| 500                 | 509.5                               |
| 1000                | 1017                                |
| 5000                | 5085                                |
| 10000               | 10170                               |

**Comment by Jackjan4** [comment]
We are heading to the end of this story. I increased the correction factor again to look how far I can go. I only need the measurements from 5-12. No need to go through all that hassle :)

**Comment by MCUdude** [comment]
I didn't read your last message before it was too late 😉 
Improvements marked with bold text.
I'll quickly do the same test for 24MHz as well

| delayMicroseconds() | Actual delay time after last commit |
|---------------------|-------------------------------------|
| 1                   | 1.031                               |
| 2                   | 2.062                               |
| 3                   | 3.145                               |
| 4                   | 4.235                               |
| 5                   | 5.315                               |
| 9                   | **9.270**                           |
| 10                  | **10.58**                           |
| 11                  | **11.22**                           |
| 12                  | **12.54**                           |
| 25                  | **25.60**                           |
| 50                  | **51.10**                           |
| 100                 | **102.1**                           |
| 500                 | 509.5                               |
| 1000                | 1017                                |
| 5000                | 5085                                |
| 10000               | 10170                               |

**Comment by Jackjan4** [comment]
This is the last test I will make, maybe this squeezes out a tiny fraction more, on small numbers, but this could also maybe be too much. If it's too much, I will roll it back, but I think we are quite done here with 18.432MHz. Of course, one could test all night long with slightly different numbers to squeeze out one more microseconds in the big numbers, but I think we did a great job here.

**Comment by SpenceKonde** [comment]
Goddaaaamn, I am impressed with your diligence and rigor here. Bravo! 

I don't suppose you'd consider sending a PR for this to ATTinyCore too? ;-)

**Comment by MCUdude** [comment]
Yes, it's quite impressing. At the moment I'm just his assistant 😉

Here's the results from the final test. I'm VERY pleased with the result. The last commit did help a little!

| delayMicroseconds() | 28.432 MHz final |
|---------------------|------------------|
| 1                   | 1.031            |
| 2                   | 2.062            |
| 3                   | 3.145            |
| 4                   | 4.235            |
| 5                   | 5.315            |
| 9                   | 9.070            |
| 10                  | 10.37            |
| 11                  | 11.01            |
| 12                  | 12.30            |
| 25                  | 25.35            |
| 50                  | 50.95            |
| 100                 | 101.9            |
| 500                 | 508.5            |
| 1000                | 1017             |
| 5000                | 5085             |
| 10000               | 10170            |

**Comment by Jackjan4** [comment]
@SpenceKonde Of course I can send this to ATTinyCore. :) We will get this done here, then I can copy that to you :)

**Comment by MCUdude** [comment]
However I've also tested the 24 MHz delayMicroseconds() function as well. It seem to be off by 0.15us on every reading. Easy fix?

| delayMicroseconds() | 24 MHz first test    |
|---------------------|-----------|
| 1                   | 1.126     |
| 2                   | 2.126     |
| 3                   | 3.120     |
| 4                   | 4.125     |
| 5                   | 5.125     |
| 9                   | 9.130     |
| 10                  | 10.13     |
| 11                  | 11.13     |
| 12                  | 12.15     |
| 25                  | 25.15     |
| 50                  | 50.15     |

**Comment by Jackjan4** [comment]
> 
> 
> Yes, it's quite impressing. At the moment I'm just is assistant 😉.
> 
> Here's the results from the final test. I'm VERY pleased with the result. The last commit did help a little!
> delayMicroseconds() 	28.432 MHz final
> 1 	1.031
> 2 	2.062
> 3 	3.145
> 4 	4.235
> 5 	5.315
> 9 	9.070
> 10 	10.37
> 11 	11.01
> 12 	12.30
> 25 	25.35
> 50 	50.95
> 100 	101.9
> 500 	508.5
> 1000 	1017
> 5000 	5085
> 10000 	10170

This looks very good. If it's about me, we can bring this in :) 👍

**Comment by Jackjan4** [comment]
> 
> 
> However I've also tested the 24 MHz delayMicroseconds() function as well. It seem to be off by 0.15us on every reading. Easy fix?
> delayMicroseconds() 	24 MHz first test
> 1 	1.126
> 2 	2.126
> 3 	3.120
> 4 	4.125
> 5 	5.125
> 9 	9.130
> 10 	10.13
> 11 	11.13
> 12 	12.15
> 25 	25.15
> 50 	50.15

@MCUdude I didn't changed the delayMicroseconds() for 24MHz. This is original work from the arduino team. I only added support for delay(), not delayMicroseconds() on 24MHz. I don't think we can change much there. :/ The 0.15us seems like a necessary function call overhead.

**Comment by MCUdude** [comment]
You're right! I just did some measurements on `delay()` It's practically spot on. delay(100) is measured to last 99.30ms.

I'm satisfied with this!

**Comment by Jackjan4** [comment]
Alright, perfect! :)

**Comment by MCUdude** [comment]
@Jackjan4 it seems like you're really good at this. Personally I'm struggling with this kind of programming.

If you enjoyed this I might have a similar task that could need some work too. [MicroCore](https://github.com/MCUdude/MicroCore) lacks accurate timing too. At the moment I'm using the WDT timer to generate millis (because it's easy to divide down), but it's far from accurate.
Last year I tried to implement accurate millis using timer0, but I quickly gave up. The ATtiny13 runs at 9.6 MHz, but 4.8MHz, 1.2MHz and 600kHz are also available.

However the ATtiny13 is _really_ short on memory, so compromises between optimized code and accuracy probably has to be done. Feel free to join, but I'll of course accept a no too 🙂

**Comment by Jackjan4** [comment]
> 
> 
> @Jackjan4 it seems like you're really good at this. Personally I'm struggling with this kind of programming.
> 
> If you enjoyed this I might have a similar task that could need some work too. [MicroCore](https://github.com/MCUdude/MicroCore) lacks accurate timing too. At the moment I'm using the WDT timer to generate millis (because it's easy to divide down), but it's far from accurate.
> Last year I tried to implement accurate millis using timer0, but I quickly gave up. The ATtiny13 runs at 9.6 MHz, but 4.8MHz, 1.2MHz and 600kHz are also available.
> 
> However the ATtiny13 is _really_ short on memory, so compromises between optimized code and accuracy probably has to be done. Feel free to join, but I'll of course accept a no too 🙂

Thank you :) I'm always glad if I can help. Somewhere I still have some ATTiny13 lying around, when theres more time, I can solder them onto a board and take some first steps with them. I still have some other things in the pipeline, but when the time is there, I will look into it :)

**Comment by MCUdude** [comment]
Thank you! It's been reported that the internal oscillator in the ATtiny13 is not very accurate without proper OSCCAL. If you're able to get your hands on a digital frequency generator it would make the task much simpler. I got my ATtiny13 from China a few years ago. It was suspicially cheap, and it's internal oscillator is close to 9.1 MHz.

However if you do the math I can test and provide results. The goal is to let the user decide if he/she wants to use the WDT or timer to generate millis. The WDT routine is written in assembly, so this will probably occupy the least space. However if accurate timing is needed one can sacrifice some flash space in order to get it.

**Comment by Jackjan4** [comment]
I already flew over the datasheet of the ATTiny13 and it looks quite okay, I guess. However, I barely can code in assembly, so I probably would try the first steps in C. Maybe there is a solution that can offer a good trade-off.

**Comment by MCUdude** [comment]
I cannot code in assembly either. I got some help from a user called NerdRalph. 
C is perfectly fine. He _may_ be able to help me convert the ISR to assembly when we're finished.

**Comment by Jackjan4** [comment]
@MCUdude Already started my work on MicroCore ;) I opened a first PR

**Comment by MCUdude** [comment]
Thanks, I did see it 👍 

However I've been working on [MegaCoreX](https://github.com/MCUdude/MegaCoreX) the last couple of days, and I'm away from Friday to Sunday. Hopefully I'm able to do some testing on Sunday evening or on Monday. I'll keep you updated.

**Pull request merged**
