### PR TITLE
delayMicroseconds for weird frequencies

### PR DESCRIPTION
**Pull request by Jackjan4**
Here's my PR for issue #18.
Since I don't have the tools to generate these frequencies, this will be a trial and error action again 😄
This first commit is experimental and is for testing.
Again, we need measurements of course :)

### CODE REVIEW

**Comment by MCUdude** [comment]
Thank you! I'll start testing tomorrow evening

**Comment by MCUdude** [comment]
Here are the first results. I'm using the following sketch:

``` c
#define DELAY 1

void setup() 
{
  DDRA |= _BV(PA7);
  cli();
}

void loop() 
{
  while(1)
  {
    PORTA = 0x80;
    delayMicroseconds(DELAY);
    PORTA = 0x00;
    delayMicroseconds(DELAY);
  } 
```

I will only provide the on-time duration since this is the most accurate one.

| delayMicroseconds | Actual time on (us) |
|-------------------|---------------------|
| 1                 | 8.140               |
| 2                 | 8.140               |
| 5                 | 8.140               |
| 25                | 8.140               |
| 30                | 8.140               |
| 31                | 8.140               |
| 35                | 8.140               |
| 36                | 24.40               |
| 100               | 93.80               |
| 200               | 202.0               |
| 500               | 527.5               |
| 1000              | 1071                |
| 2000              | 2154                |
| 5000              | 5415                |
| 10000             | 10830               |

**Comment by MCUdude** [comment]
The comments in the code is also incorrect

```
	  // for the weird 1.8432 MHz clock
	  // 1 cycle takes 1.8432 microseconds
	  // in 1 micro 0.542534 cycles are executed
```

A 1.8432 MHz clock means 1 instruction is executed in 0.542534 microseconds, not the opposite.

**Comment by Jackjan4** [comment]
Yes, the comment is wrong. I already fixed it for my next commit

**Comment by MCUdude** [comment]
Thanks!

Do you have any idea why the duration was 8.140us even from 1 to 35 us? I thought
```
if (us <= 30) return;
```

would kick in and cause a longer delay. I'm compiling with LTO disabled.

**Comment by MCUdude** [comment]
When do you think we have all this implemented? There's an [issue](https://github.com/MCUdude/MightyCore/issues/140) with the last release of MightyCore where some libraries don't play well with PlatfromIO.

I need to release new MightyCore version soon, but it would be great if I also could provide new supported clock frequencies as well. However, I feel can't wait many weeks before I do a new release.

**Comment by Jackjan4** [comment]
> 
> 
> Thanks!
> 
> Do you have any idea why the duration was 8.140us even from 1 to 35 us? I thought
> 
> ```
> if (us <= 30) return;
> ```
> 
> would kick in and cause a longer delay. I'm compiling with LTO disabled.

Probably (since your are using a constant DELAY time) one of the if statements is not compiled

**Comment by MCUdude** [comment]
Well, I'm still seeing the same pattern.

``` c
uint16_t delay_value = 10;

void setup() 
{
  DDRA |= _BV(PA7);
  cli();
}

void loop() 
{
  while(1)
  {
    PORTA = 0x80;
    delayMicroseconds(delay_value);
    PORTA = 0x00;
    delayMicroseconds(delay_value);
  } 
}
```


| delayMicroseconds | Actual time on (us) |
|-------------------|---------------------|
| 1                 | 9.220               |
| 2                 | 9.220               |
| 5                 | 9.220               |
| 25                | 9.220              |
| 30                | 9.220               |
| 31                | 9.220               |
| 35                | 9.220               |
| 36                | 25.50               |
| 100               | 94.80               |
| 200               | 203.2               |
| 500               | 528.5              |
| 1000              | 1071                |
| 2000              | 2158                |
| 5000              | 5415                |
| 10000             | 10830               |

**Comment by Jackjan4** [comment]
I think optimizations are still being done in the compiler, since it can predicate your value (since it never changes). Maybe counting your variable would do?

**Comment by Jackjan4** [comment]
> 
> 
> When do you think we have all this implemented? There's an [issue](https://github.com/MCUdude/MightyCore/issues/140) with the last release of MightyCore where some libraries don't play well with PlatfromIO.
> 
> I need to release new MightyCore version soon, but it would be great if I also could provide new supported clock frequencies as well. However, I feel can't wait many weeks before I do a new release.

If we get this frequency accurate and everything works well, we can use the fact that the frequencies add up together to get everything accurate very quick. This low frequency is a bit tricky to get right but I think we should get this done in this week :)

**Comment by Jackjan4** [comment]
This second commit a bit more accurate on the mathematical side. Hopefully this works out okay.

**Comment by MCUdude** [comment]
I can add 

``` c
#pragma GCC push_options
#pragma GCC optimize ("O0")

 void delayMicroseconds(unsigned int us) {/*code*/}

#pragma GCC pop_options
```

around the delayMicroseconds function. This will prevent the compiler from optimizing code away.

**Comment by MCUdude** [comment]
Well, when trying to run a delay of 10us I get an actual delay of 142ms! Something is clearly wrong here.

**Comment by Jackjan4** [comment]
Oh well, what?!
Try the new commit. Maybe you should turn the GCC options off again, maybe they cause some weirdness?

EDIT: Yes you're right, it was my fault. I missed to remove a wrong subtraction, thus creating a huge number.

**Comment by MCUdude** [comment]
I figured out if I turn off GCC optimization (adding #pragma) then I mess up accurate timing for all the other clock frequencies as well. GCC doesn't allow #pragma inside functions.

The last commit fixes the issue though (which ONLY appeared at 10us).
Don't worry about the formatting for now. We can fix all this in a single commit later 😉 
Here are the results (with GCC optimization):

| delayMicroseconds | Actual time on (us) |
|-------------------|---------------------|
| 1                 | 9.220               |
| 10                | 9.220               |
| 14                | 12.48               |
| 15                | 12.48               |
| 20                | 18.96               |
| 50                | 51.50               |
| 100               | 105.6               |
| 200               | 214.1               |
| 500               | 539.5               |
| 1000              | 1083                |
| 2000              | 2166                |
| 5000              | 5425                |
| 10000             | 10850               |

**Comment by Jackjan4** [comment]
Alright, looks way better in the 1-50 section. The next commit targets the inaccuracy in the big numbers.

**Comment by MCUdude** [comment]
Last results:

| delayMicroseconds | Actual time on (us) |
|-------------------|---------------------|
| 1                 | 9.220               |
| 10                | 9.220               |
| 14                | 26.00               |
| 15                | 26.00               |
| 20                | 32.50               |
| 50                | 60.80               |
| 100               | 108.4               |
| 200               | 203.6               |
| 500               | 488.5               |
| 1000              | 963.0               |
| 2000              | 1910                |
| 5000              | 4765                |
| 10000             | 9510                |

**Comment by Jackjan4** [comment]
We are getting closer. A bit too much this time. Try the next commit. Maybe this could be it.

**Comment by MCUdude** [comment]
New results:

| delayMicroseconds | Actual time on (us) |
|-------------------|---------------------|
| 1                 | 9.220               |
| 10                | 9.220               |
| 14                | 28.70               |
| 15                | 28.70               |
| 20                | 35.20               |
| 50                | 65.60               |
| 100               | 117.6               |
| 200               | 219.6               |
| 500               | 523.5               |
| 1000              | 1033                |
| 2000              | 2050                |
| 5000              | 5105                |
| 10000             | 10190               |

**Comment by Jackjan4** [comment]
Large numbers look good. Now fine tuning the times.

**Comment by MCUdude** [comment]
Results from last commit:

| delayMicroseconds | Actual time on (us) |
|-------------------|---------------------|
| 1                 | 9.220               |
| 10                | 9.220               |
| 15                | 9.220               |
| 16                | 45.50               |
| 20                | 49.90               |
| 50                | 80.20               |
| 100               | 134.4               |
| 200               | 238.5               |
| 500               | 555.5               |
| 1000              | 1081                |
| 2000              | 2130                |
| 5000              | 5285                |
| 10000             | 10550               |

**Comment by Jackjan4** [comment]
Oh what, this even did the opposite of what it was supposed to do. Next commit is reverting it back and doing finer steps in the other direction.

**Comment by MCUdude** [comment]
I'm sorry. The last results are wrong. I did some tweaking on the code myself while waiting for your response, and totally forgot to remove it before I ran the test again. The following results are from this code:

```c
#elif F_CPU >= 1843200L
	  // for the weird 1.8432 MHz clock
	  // 1 cycle takes 1.8432 microseconds
	  // in 1 micro 0.542534 cycles are executed
	
	 if (us <= 9) return;
	 if (us <= 15) return; //= 3 cycles, (4 when true) (must be at least 14 if we want to substract 12)
	
	  // Compensate for the time taken by the preceeding and next commands (about 22 cycles / 12us)
	  us -= 14; // = 2 cycles
	
	  // the following loop takes 2.17 microseconds (4 cycles)
	  // per iteration, so execute it us/2 (actually us/1.8432) times
	  // for each microsecond request
	
	  // us is at least 10
	  us = (us >> 1) - (us >> 5);
```

| delayMicroseconds | Actual time on (us) |
|-------------------|---------------------|
| 1                 | 9.220               |
| 10                | 9.220               |
| 15                | 9.220               |
| 16                | 28.70               |
| 20                | 33.00               |
| 50                | 63.40               |
| 100               | 115.2               |
| 200               | 217.2               |
| 500               | 521.5               |
| 1000              | 1031                |
| 2000              | 2046                |
| 5000              | 5105                |
| 10000             | 10190               |



Do you want me to test the code from the latest commit as well, or do you rather want to do changes based on these (correct) results?

**Comment by Jackjan4** [comment]
No, you don't need to test the correction. I will re-revert it back 😆
The next commit is fine tuning even more. I will do this in good steps until the lower numbers are on point. The big numbers won't probably change anymore. (maybe only by a little bit)

**Comment by MCUdude** [comment]
New results:

| delayMicroseconds | Actual time on (us) |
|-------------------|---------------------|
| 1                 | 9.220               |
| 10                | 9.220               |
| 15                | 9.220               |
| 18                | 28.70               |
| 20                | 30.90               |
| 50                | 61.20               |
| 100               | 113.2               |
| 200               | 215.2               |
| 500               | 519.5               |
| 1000              | 1029                |
| 2000              | 2046                |
| 5000              | 5095                |
| 10000             | 10190               |

**Comment by Jackjan4** [comment]
Okay, now we have to make a decision. Since the clock is too low to go in precise for all numbers by design of the delayMicroseconds function we need to decide whether we get accurate medium numbers (20-99) and kill off the low numbers (like 1-17, they all get 9.22us) or we let the small numbers survive (with a much bigger actual time), but the medium numbers won't be as accurate. I could fine tune even more the medium numbers, but every time we loose 2 more small numbers to the 9.22us

**Comment by MCUdude** [comment]
Just out of curiosity I tweaked the us bitshift line a little:
```
us = (us >> 1) - (us >> 5) - (us >> 6) + (us >> 7);
```

By doing this accuracy over the entire range was improved. It's still off for the lower numbers, but I think it looks pretty good. Do you want me to post a full table with this "new" line?

**Comment by Jackjan4** [comment]
> 
> 
> Just out of curiosity I tweaked the us bitshift line a little:
> 
> ```
> us = (us >> 1) - (us >> 5) - (us >> 6) + (us >> 7);
> ```
> 
> By doing this accuracy over the entire range was improved. It's still off for the lower numbers, but I think it looks pretty good. Do you want me to post a full table with this "new" line?

Looks really good, didn't tried that because I had the fear that this could introduce too many instruction cycles to the whole thing. Yes, a table would be great! :)

**Comment by MCUdude** [comment]
EDIT: forget all this! My text editor has messed up big time! I don't know what just happened, and the line above just made everything way too slow. I think there was a problem with saving the file.

Anyways I restarted the text editor. The code now looks like this:

```c
#elif F_CPU >= 1843200L
	  // for the weird 1.8432 MHz clock
	  // 1 cycle takes 1.8432 microseconds
	  // in 1 micro 0.542534 cycles are executed
	
	 if (us <= 9) return;
	 if (us <= 17) return; //= 3 cycles, (4 when true) (must be at least 14 if we want to substract 12)
	
	  // Compensate for the time taken by the preceeding and next commands (about 22 cycles / 12us)
	  us -= 16; // = 2 cycles
	
	  // the following loop takes 2.17 microseconds (4 cycles)
	  // per iteration, so execute it us/2 (actually us/1.8432) times
	  // for each microsecond request
	
	  // us is at least 10
	  us = (us >> 1);
```

Here's the result:

| delayMicroseconds | Actual time on (us) |
|-------------------|---------------------|
| 1                 | 9.220               |
| 10                | 9.220               |
| 15                | 9.220               |
| 18                | 12.40               |
| 20                | 14.40               |
| 50                | 47.20               |
| 100               | 101.4               |
| 200               | 209.6               |
| 500               | 535.5               |
| 1000              | 1078                |
| 2000              | 2162                |
| 5000              | 5415                |
| 10000             | 10850               |

**Comment by MCUdude** [comment]
The midrange is pretty accurate, but the low numbers are a bit too fast while the big numbers are a bit too slow

**Comment by Jackjan4** [comment]
The last line in your snippet seems to be wrong. It shouldn't be
`  us = (us >> 1);`

instead it should be
`us = (us >> 1) - (us >> 5);`

(or your variant)

**Comment by MCUdude** [comment]
Damnit! OK, clean slate. This is the code we're working on:

```c
#elif F_CPU >= 1843200L
	  // for the weird 1.8432 MHz clock
	  // 1 cycle takes 1.8432 microseconds
	  // in 1 micro 0.542534 cycles are executed
	
	 if (us <= 9) return;
	 if (us <= 17) return; //= 3 cycles, (4 when true) (must be at least 14 if we want to substract 12)
	
	  // Compensate for the time taken by the preceeding and next commands (about 22 cycles / 12us)
	  us -= 16; // = 2 cycles
	
	  // the following loop takes 2.17 microseconds (4 cycles)
	  // per iteration, so execute it us/2 (actually us/1.8432) times
	  // for each microsecond request
	
	  // us is at least 10
	  us = (us >> 1) - (us >> 5);
```

These are the results for the code above:

| delayMicroseconds | Actual time on (us) |
|-------------------|---------------------|
| 1                 | 9.220               |
| 10                | 9.220               |
| 15                | 9.220               |
| 18                | 28.70               |
| 20                | 30.90               |
| 50                | 61.20               |
| 100               | 113.2               |
| 200               | 215.2               |
| 500               | 519.5               |
| 1000              | 1029                |
| 2000              | 2046                |
| 5000              | 5095                |
| 10000             | 10190               |

**Comment by Jackjan4** [comment]
And your line:
`us = (us >> 1) - (us >> 5) - (us >> 6) + (us >> 7);`
was way too slow?

**Comment by MCUdude** [comment]
Here are the results where (us >> 7) is both added and subtracted.

```c
us = (us >> 1) - (us >> 5) - (us >> 6) - (us >> 7);
```

| delayMicroseconds | Actual time on (us) |
|-------------------|---------------------|
| 500               | 519.5               |
| 1000              | 1003                |
| 2000              | 1966                |
| 5000              | 4875                |
| 10000             | 9690                |


<br/>
<br/>

```c
us = (us >> 1) - (us >> 5) - (us >> 6) + (us >> 7);
```

| delayMicroseconds | Actual time on (us) |
|-------------------|---------------------|
| 500               | 540                 |
| 1000              | 1033                |
| 2000              | 2030                |
| 5000              | 5035                |
| 10000             | 10030               |

**Comment by MCUdude** [comment]
I've experimented some more. I used the 18.432 MHz code as a base, and just tweaked until I found the results ok. What do you think? 

```c
#elif F_CPU >= 1843200L
	  // for the weird 1.8432 MHz clock
	  // 1 cycle takes 1.8432 microseconds
	  // in 1 micro 0.542534 cycles are executed
	
	if (us <= 10) return; 
	

  if (us > 41) { 
    us = (us >> 1) - (us >> 4) + (us >> 5) - (us >> 7); 
    us -= 19;
    
  } else { 

    us -= 8;
    us = (us >> 1); 
  }
```

| delayMicroseconds | Actual time on (us) |
|-------------------|---------------------|
| 1                 | 9.220               |
| 10                | 9.220               |
| 20                | 25.50               |
| 30                | 36.30               |
| 41                | 47.20               |
| 42                | 48.20               |
| 50                | 54.70               |
| 100               | 106.8               |
| 200               | 206.6               |
| 500               | 506.5               |
| 1000              | 1007                |
| 2000              | 2006                |
| 5000              | 5006                |
| 10000             | 10010               |

Can you see any room for improvements here?

**Comment by Jackjan4** [comment]
This is perfect. I couldn't have done it better. I think this is it :) I dont think we can get much better since the clock is so low that a loop cycle takes 2.1us, which is our granularity. And at 10000us we are only 10us off which is only 4 loop cycles.

**Comment by MCUdude** [comment]
I feel like I understand more of this magic now. Especially after you learned me how to do advanced bitshift multiplication and division!

I started working on the 3.6864 MHz clock. It's becoming very accurate, so I'm almost there. But do you know what number to subtract from `us`? Now I'm subtracting 4 and 16, but it's just a wild guess.

``` c
#elif F_CPU >= 3686400L
	
if (us <= 5) return; 

  else if (us < 31) 
  { 
    us -= 4;
    us = (us >> 1) + (us >> 2); 
  }	

  else 
  { 
    us = us - (us >> 4)- (us >> 6);
    us -= 16;  
  } 
```

**Comment by Jackjan4** [comment]
> 
> 
> I feel like I understand more of this magic now. Especially after you learned me how to do advanced bitshift multiplication and division!
> 
> I started working on the 3.6864 MHz clock. It's becoming very accurate, so I'm almost there. But do you know what number to subtract from `us`? Now I'm subtracting 4 and 16, but it's just a wild guess.
> 
> ```c
> #elif F_CPU >= 3686400L
> 	
> if (us <= 5) return; 
> 
>   else if (us < 31) 
>   { 
>     us -= 4;
>     us = (us >> 1) + (us >> 2); 
>   }	
> 
>   else 
>   { 
>     us = us - (us >> 4)- (us >> 6);
>     us -= 16;  
>   } 
> ```

To be honest, most of the time I'm also guessing what to subtract. 
The rule is: subtract the number of microseconds you wasted with your function.
However to count the cycle count of the function (to get your wasted us) you have to either know what every instruction is doing or to look at the assembly code (tried that once but wasn't really sucessfull).
A rule of thumb is that most things use 1 instruction (subtraction, addition, assigning).
If-statement takes 3 (4 when true). Function overhead is 16 cycles. Bitshifting uses 3.

So for example:
`us -= 4`
takes 2 instructions (assinging, subtraction)

**Comment by Jackjan4** [comment]
> 
> 
> I've experimented some more. I used the 18.432 MHz code as a base, and just tweaked until I found the results ok. What do you think?
> 
> ```c
> #elif F_CPU >= 1843200L
> 	  // for the weird 1.8432 MHz clock
> 	  // 1 cycle takes 1.8432 microseconds
> 	  // in 1 micro 0.542534 cycles are executed
> 	
> 	if (us <= 10) return; 
> 	
> 
>   if (us > 41) { 
>     us = (us >> 1) - (us >> 4) + (us >> 5) - (us >> 7); 
>     us -= 19;
>     
>   } else { 
> 
>     us -= 8;
>     us = (us >> 1); 
>   }
> ```
> 
> delayMicroseconds 	Actual time on (us)
> 1 	9.220
> 10 	9.220
> 20 	25.50
> 30 	36.30
> 41 	47.20
> 42 	48.20
> 50 	54.70
> 100 	106.8
> 200 	206.6
> 500 	506.5
> 1000 	1007
> 2000 	2006
> 5000 	5006
> 10000 	10010
> 
> Can you see any room for improvements here?

I thought about what happens if you don't subtract 19 but a larger number. Does this maybe improve it a bit more? Actually it maybe should be.

**Comment by MCUdude** [comment]
> I thought about what happens if you don't subtract 19 but a larger number. Does this maybe improve it a bit more? Actually, it maybe should be.

You're right. This can be improved even more. It was getting very late, so I missed this. New results for 1.8432 MHz commming very soon!

**Comment by MCUdude** [comment]
Ok, this is awesome! I did some more tweaking, and it's basically perfect now!

``` c
#elif F_CPU >= 1843200L
	
  if (us <= 13) 
    return; 
	
  else if(us <= 49) 
  { 
    us -= 12;
    us = (us >> 1); 
  }

  else 
  { 
    us = (us >> 1) - (us >> 4) + (us >> 5) - (us >> 7); 
    us -= 21;  
  }
```

| delayMicroseconds | Actual on time [us] |
|-------------------|---------------------|
| 1                 | 9.220               |
| 13                | 9.220               |
| 14                | 15.189              |
| 20                | 21.699              |
| 30                | 32.551              |
| 50                | 49.912              |
| 100               | 101.99              |
| 200               | 201.82              |
| 500               | 501.30              |
| 1000              | 1002.60             |
| 2000              | 2000.88             |
| 5000              | 5002.13             |
| 10000             | 10002.15            |

**Comment by MCUdude** [comment]
However, I'm struggling with writing decent comments here. One thing is explaining what we multiply with, but another thing is the instructions we "burn away"  (and increasing the delay) when doing all this bit shifting. 

To be honest I don't have full control of the actual instruction count for each part of this code. If I did I didn't have to do so much testing because theory and practice would be the same 😉

**Comment by Jackjan4** [comment]
Very good, we should keep this good solution then. If you want I can add comments to this.

**Comment by MCUdude** [comment]
That would be great! I'll see if I can finish the code for 7.3728 and 14.7456 first, and then you could add comments to all of them. I'll post the entire code when I'm done!

**Comment by Jackjan4** [comment]
Alright, I'm excited!

**Comment by MCUdude** [comment]
Here's the finished code! If you re-post the code here with the comments I can go through the formatting to make sure no tabs or end line spaces have snuck into the code.

EDIT:
I also added 2 MHz and 4 MHz clocks.

``` c
#elif F_CPU >= 14745600L
  if (us <= 2) 
    return; 
  else if (us <= 9) 
  {
    us -= 2;
    us = (us << 2);
  }	
  else 
  { 
    us = (us << 2) - (us >> 2) - (us >> 4);
    us -= 16;
     __asm__ __volatile__ (
    "nop" "\n\t"
    "nop" "\n\t"
    "nop"); // Wait 3 cycles
  } 

#elif F_CPU >= 7372800L
  if (us <= 2) 
    return;

  else if (us <= 12) 
  {
    us -= 2;
    us = us + (us >> 1) - (us >> 4); 
  }

  else 
  { 
    us = (us << 1) - (us >> 3) - (us >> 4) + (us >> 5);
    us -= 24;  
  } 

#elif F_CPU >= 4000000L
  if (us <= 2) 
    return; 

  us -= 2; 

#elif F_CPU >= 3686400L
  if (us <= 7) 
    return;

  else if (us <= 30) 
  { 
    us -= 6;
    us = (us >> 1) + (us >> 2) - (us >> 5); 
  }

  else 
  { 
    us = us - (us >> 4) - (us >> 6);
    us -= 16;  
  }

#elif F_CPU >= 2000000L
  if (us <= 13) 
    return;

  us -= 11;
  us = (us >> 1);

#elif F_CPU >= 1843200L
  if (us <= 13) 
    return;
 
  else if(us <= 49) 
  { 
    us -= 12;
    us = (us >> 1); 
  }

  else 
  { 
    us = (us >> 1) - (us >> 4) + (us >> 5) - (us >> 7); 
    us -= 21;  
  }
```

**Comment by Jackjan4** [comment]
```c++
#elif F_CPU >= 14745600L
  // 14.7456MHz clock
  
  // The overhead of the function call is 14 (16) cycles which is ~1 us
  if (us <= 2) 
    return; 

  else if (us <= 9) 
  {
	// The requested microseconds are too small to multiplicate correct, so we do an approximation
    us -= 2;
	// Subtract microseconds that were wasted in this function
    us = (us << 2);
  }	
  else 
  {
	// The following loop takes 0.27126 microseconds (4 cycles)
    // per iteration, so execute it us*3.6864 times
    // for each microsecond requested
    us = (us << 2) - (us >> 2) - (us >> 4); // multiply with 3.6875
    us -= 16; // Subtract microseconds that were wasted in this function
	
     __asm__ __volatile__ (
    "nop" "\n\t"
    "nop" "\n\t"
    "nop"); // Wait 3 cycles to accomodate imprecisions in approximation
  } 

#elif F_CPU >= 7372800L
  // 7.3728MHz clock
  
  // The overhead of the function call is 14 (16) cycles which is ~2 us
  if (us <= 2) 
    return;

  
  else if (us <= 12) 
  {
	// The requested microseconds are too small to multiplicate correct, so we do an approximation
    us -= 2; // Subtract microseconds that were wasted in this function
    us = us + (us >> 1) - (us >> 4); 
  }

  else 
  {
	// The following loop takes 0.5425 microseconds (4 cycles)
    // per iteration, so execute it us*1.8432 times
    // for each microsecond requested
    us = (us << 1) - (us >> 3) - (us >> 4) + (us >> 5); // multiply with 1.84375
    us -= 24;  
  } 

#elif F_CPU >= 4000000L
  // 4MHz clock
  
  // The overhead of the function call is 14 (16) cycles which is 4 us
  if (us <= 2) 
    return; 

  // Subtract microseconds that were wasted in this function
  us -= 2;
  
  // We don't need to multiply here because one request microsecond is exactly one loop cycle

#elif F_CPU >= 3686400L
  // 3.6864MHz clock
  // The overhead of the function call is 14 (16) cycles which is ~6 us
  if (us <= 7) 
    return;

  else if (us <= 30) 
  {
	// The requested microseconds are too small to multiplicate correct, so we do an approximation
    us -= 6; // Subtract microseconds that were wasted in this function
    us = (us >> 1) + (us >> 2) - (us >> 5); // multiply with 0.71875
  }

  else 
  {
	// The following loop takes 1.085 microseconds (4 cycles)
    // per iteration, so execute it us*0.9216 times
    // for each microsecond requested
    us = us - (us >> 4) - (us >> 6); // multiply with 0.9216
    us -= 16;  // Subtract microseconds that were wasted in this function
  }

#elif F_CPU >= 2000000L
  // 2MHz Clock
  
  
  if (us <= 13)
	// The overhead of the function call is 14 (16) cycles which is 8.68 us
	// Plus the if-statement that takes 3 cycles (4 when true): ~11us
    return;

  // Subtract microseconds that were wasted in this function
  us -= 11; // 2 cycles
  
  us = (us >> 1); // 3 cycles

#elif F_CPU >= 1843200L
  // For the weird 1.8432 MHz clock
  // 1 cycle takes 0.542534 microseconds
  // in 1 micro 1.8432 cycles are executed
  
  if (us <= 13)
	// The overhead of the function call is 14 (16) cycles which is 8 us
	// Plus the if-statement that takes 3 cycles (4 when true): ~10us
    return;
 
  else if(us <= 49) 
  {
	// The requested microseconds are too small to multiplicate correct, so we do an approximation
	// The following loop takes 2.17 microseconds (4 cycles)
    // per iteration, so execute it actually us/2 times
    // for each microsecond requested
    us -= 12;
    us = (us >> 1); 
  }

  else 
  {
      // The following loop takes 2.17 microseconds (4 cycles)
      // per iteration, so execute it actually us/2.17 or in different words us*0.4608 times
      // for each microsecond requested
    us = (us >> 1) - (us >> 4) + (us >> 5) - (us >> 7);
	
	// Subtract microseconds that were wasted in this function
    us -= 21;  
  }
```

Here it is with comments, but you have to do the formatting again since I did it in a text editor 🙄

**Comment by MCUdude** [comment]
Thank you so much! I'll fix the formatting, no worries!

**Comment by MCUdude** [comment]
See commit e11435e

**Pull request closed without merging**
