### PR TITLE
More accurate delay() and delayMicroseconds() for 32MHz

### PR DESCRIPTION
**Pull request by Jackjan4**
New PR, new accurate frequency 😋 32MHz is the extreme case and I only do this PR because 32MHz resonators work surprisingly well with the ATmegas.

### CODE REVIEW

**Comment by MCUdude** [comment]
Really? 32 MHz? I don't have any crystal I can use to test this. However I think the code is pretty straight forward.

**Comment by Jackjan4** [comment]
I also only had one 32MHz resonator left I could test this with. These little guys are quite expensive in ceramic type. Yes, the code is just a copy of the 24MHz code with the slight change in multiplication to fit 32MHz, nothing new going on there.

**Comment by MCUdude** [comment]
So why no micros() support? is it simply too fast?

**Comment by Jackjan4** [comment]
micros() support is included in this PR. Maybe its not too obvious in the code, but since 32 divides 64 evenly, the original arduino code will run and do its thing there.

**Comment by MCUdude** [comment]
Ah, of course! Have you actually tested this on real hardware just to make sure ir really is accurate (it should be though)?

**Comment by Jackjan4** [comment]
Yes, I tested it. It works just as accurate as all the other even clocks. I can provide a measurement table tomorrow, if needed.

**Comment by MCUdude** [comment]
No need, I believe you 😉 
However you probably won't see a 32 MHz option in any of my cores any time soon. I prefer to keep them within spec. However it's great that the underlying core files actually supports overclocking if you have a specific project that really needs 24 or 32 MHz (VGA screens for instance).

**Comment by Jackjan4** [comment]
Yeah, of course. This PR wasn't intended to be used as a selectable option for a bootloader supported core. This is definitly only for advanced overclocking. And if theres a time someone needs this speed, we have it :)

**Pull request merged**
